var empName = 'Manoj';
console.log("The employee name is ".concat(empName));
var age = 28;
console.log("The age is ".concat(age));
var browser = 'chrome';
console.log(browser);
var x = undefined;
var y = null;
console.log(x);
console.log(y);
